# Generated by Django 4.2.9 on 2024-02-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vezeteknev',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
