# Generated by Django 4.2.9 on 2024-02-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_customer_vezeteknev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vezeteknev',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.customer'),
        ),
    ]
