# Generated by Django 4.2.9 on 2024-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_remove_customer_vezeteknev_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='allapot',
            field=models.CharField(choices=[('--válasszon--', '--Válasszon--'), ('bontatlan', 'Bontatlan'), ('újszerű', 'Újszerű'), ('használt', 'Használt'), ('megviselt', 'Megviselt')], default='--válasszon--', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='feladocim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feladoorszag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('--válasszon--', '--Válasszon--'), ('autó', 'Autó'), ('élelmiszer', 'Élelmiszer'), ('egyéb', 'Egyéb')], default='--válasszon--', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
