# Generated by Django 4.2.9 on 2024-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='kep',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='leiras',
        ),
        migrations.AddField(
            model_name='product',
            name='terms_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
