# Generated by Django 4.2.9 on 2024-02-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0008_rename_image_product_kep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='leiras',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kep',
            new_name='image',
        ),
    ]
