# Generated by Django 4.2.9 on 2024-02-12 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_customer_firstname_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='ervenytelen_szam', message='A telefonszám csak számokat, illetve + karaktert tartalmazhat', regex='^[\\d()+-]*$')]),
        ),
    ]
