# Generated by Django 4.2.9 on 2024-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_remove_customer_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='leiras',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
