# Generated by Django 4.2.9 on 2024-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0017_alter_topic_leiras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='leiras',
            field=models.CharField(default='Ehhez a témához nem tartozik leírás', max_length=75, null=True),
        ),
    ]
