# Generated by Django 4.2.9 on 2024-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0022_rename_email_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
    ]
