# Generated by Django 4.2.9 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0025_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
