# Generated by Django 4.2.9 on 2024-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0026_product_received_product_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('--válasszon--', '--Válasszon--'), ('autó', 'Autó'), ('élelmiszer', 'Élelmiszer'), ('elektronika', 'Elektronika'), ('bútor', 'Bútor'), ('könyv', 'Könyv'), ('egyéb', 'Egyéb')], default='--válasszon--', max_length=50),
        ),
    ]
