# Generated by Django 5.0.1 on 2024-02-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("default", "0028_product_orderer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
