# Generated by Django 5.0.1 on 2024-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("default", "0029_alter_topic_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
