# Generated by Django 5.0.1 on 2024-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("default", "0030_alter_product_description_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="banned_ad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="banned_forum",
            field=models.BooleanField(default=False),
        ),
    ]
